### ISSUE TITLE
Add support for a YAML configuration file

### ISSUE THREAD

**Issue by scottbrown** [scottbrown/beacon#45]
The YAML configuration file would help to cut down on duplicate data passed as flags, such a `--project` and `--instance-id`.  The YAML file could be as simple as:

```yaml
---
beacon:
  project: "Test Project"
  instanceID: "i-xxxxxxx"
```

The configuration file can be specified in either a `-f` flag or in a common place such as `/etc/beacon/config`.
